### ISSUE TITLE
Error installing boss-cli==0.2.1 due to README.md error

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/boss-cli#22]
Got this error while trying to install `boss-cli==0.2.1`
```
suresh@suresh-lf /var/www/html/abc/xyz (SL-237) $ sudo pip install boss-cli==0.2.1
The directory '/home/suresh/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/suresh/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting boss-cli==0.2.1
  Downloading boss-cli-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qGYz3c/boss-cli/setup.py", line 14, in <module>
        with open(join(this_dir, 'README.md'), encoding='utf-8') as file:
      File "/usr/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-qGYz3c/boss-cli/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qGYz3c/boss-cli/
```

**Comment by kabirbaidhya** [comment]
Resolved in https://github.com/kabirbaidhya/boss-cli/commit/4993863a949bd58518cf8fd43b5514cd8f9931c9
